version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 651199432378.dkr.ecr.eu-central-1.amazonaws.com/youtube:latest
  post_build:
    commands:
      - docker push 651199432378.dkr.ecr.eu-central-1.amazonaws.com/youtube:latest
      - printf '[{"name":"my-task-definition","imageUri":"%s"}]' 651199432378.dkr.ecr.eu-central-1.amazonaws.com/youtube:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
